// GENERIERT aus tokens/tokens.json — NICHT bearbeiten (INV-H2).
//
// Konsum in Klasse B (Modeler/Viewer): Renderer beziehen Farben und Metriken
// ausschließlich hierüber bzw. über die CSS-Variablen (INV-H2).

export const light = {
  "color-bg": "#ffffff",
  "color-surface": "#f5f6f8",
  "color-surface-raised": "#ffffff",
  "color-overlay": "rgba(16, 18, 21, 0.45)",
  "color-fg": "#1a1d21",
  "color-fg-muted": "#5a6169",
  "color-fg-subtle": "#8b929b",
  "color-border": "#d5d9de",
  "color-border-strong": "#b6bcc4",
  "color-accent": "#2f6feb",
  "color-accent-fg": "#ffffff",
  "color-accent-muted": "#dbe6ff",
  "color-success": "#1a7f37",
  "color-success-fg": "#ffffff",
  "color-warning": "#9a6700",
  "color-warning-fg": "#ffffff",
  "color-danger": "#cf222e",
  "color-danger-fg": "#ffffff",
  "color-info": "#0969da",
  "color-info-fg": "#ffffff",
  "color-focus-ring": "#2f6feb",
  "space-0": "0",
  "space-1": "4px",
  "space-2": "8px",
  "space-3": "12px",
  "space-4": "16px",
  "space-5": "20px",
  "space-6": "24px",
  "space-8": "32px",
  "space-10": "40px",
  "space-12": "48px",
  "space-16": "64px",
  "space-px": "1px",
  "radius-none": "0",
  "radius-sm": "4px",
  "radius-md": "8px",
  "radius-lg": "12px",
  "radius-xl": "16px",
  "radius-full": "9999px",
  "elevation-0": "none",
  "elevation-1": "0 1px 2px rgba(16, 18, 21, 0.08)",
  "elevation-2": "0 2px 6px rgba(16, 18, 21, 0.12)",
  "elevation-3": "0 8px 24px rgba(16, 18, 21, 0.16)",
  "text-family-sans": "system-ui, -apple-system, Segoe UI, Roboto, sans-serif",
  "text-family-mono": "ui-monospace, SFMono-Regular, Menlo, monospace",
  "text-size-xs": "12px",
  "text-size-sm": "13px",
  "text-size-md": "14px",
  "text-size-lg": "16px",
  "text-size-xl": "20px",
  "text-size-2xl": "28px",
  "text-weight-regular": "400",
  "text-weight-medium": "500",
  "text-weight-semibold": "600",
  "text-weight-bold": "700",
  "text-leading-tight": "1.2",
  "text-leading-normal": "1.5",
  "text-leading-relaxed": "1.7",
  "motion-duration-instant": "0ms",
  "motion-duration-fast": "120ms",
  "motion-duration-normal": "200ms",
  "motion-duration-slow": "320ms",
  "motion-ease-standard": "cubic-bezier(0.2, 0, 0, 1)",
  "motion-ease-decelerate": "cubic-bezier(0, 0, 0, 1)",
  "motion-ease-accelerate": "cubic-bezier(0.3, 0, 1, 1)",
} as const;

export const dark = {
  "color-bg": "#0e1116",
  "color-surface": "#161b22",
  "color-surface-raised": "#1c232c",
  "color-overlay": "rgba(0, 0, 0, 0.6)",
  "color-fg": "#e6e8eb",
  "color-fg-muted": "#9aa4af",
  "color-fg-subtle": "#6b7580",
  "color-border": "#2a313a",
  "color-border-strong": "#3a434e",
  "color-accent": "#5b8cff",
  "color-accent-fg": "#0b1220",
  "color-accent-muted": "#1d2b4d",
  "color-success": "#3fb950",
  "color-success-fg": "#02180a",
  "color-warning": "#d29922",
  "color-warning-fg": "#1a1300",
  "color-danger": "#f85149",
  "color-danger-fg": "#1a0202",
  "color-info": "#58a6ff",
  "color-info-fg": "#02121f",
  "color-focus-ring": "#5b8cff",
  "space-0": "0",
  "space-1": "4px",
  "space-2": "8px",
  "space-3": "12px",
  "space-4": "16px",
  "space-5": "20px",
  "space-6": "24px",
  "space-8": "32px",
  "space-10": "40px",
  "space-12": "48px",
  "space-16": "64px",
  "space-px": "1px",
  "radius-none": "0",
  "radius-sm": "4px",
  "radius-md": "8px",
  "radius-lg": "12px",
  "radius-xl": "16px",
  "radius-full": "9999px",
  "elevation-0": "none",
  "elevation-1": "0 1px 2px rgba(0, 0, 0, 0.5)",
  "elevation-2": "0 2px 8px rgba(0, 0, 0, 0.6)",
  "elevation-3": "0 10px 30px rgba(0, 0, 0, 0.7)",
  "text-family-sans": "system-ui, -apple-system, Segoe UI, Roboto, sans-serif",
  "text-family-mono": "ui-monospace, SFMono-Regular, Menlo, monospace",
  "text-size-xs": "12px",
  "text-size-sm": "13px",
  "text-size-md": "14px",
  "text-size-lg": "16px",
  "text-size-xl": "20px",
  "text-size-2xl": "28px",
  "text-weight-regular": "400",
  "text-weight-medium": "500",
  "text-weight-semibold": "600",
  "text-weight-bold": "700",
  "text-leading-tight": "1.2",
  "text-leading-normal": "1.5",
  "text-leading-relaxed": "1.7",
  "motion-duration-instant": "0ms",
  "motion-duration-fast": "120ms",
  "motion-duration-normal": "200ms",
  "motion-duration-slow": "320ms",
  "motion-ease-standard": "cubic-bezier(0.2, 0, 0, 1)",
  "motion-ease-decelerate": "cubic-bezier(0, 0, 0, 1)",
  "motion-ease-accelerate": "cubic-bezier(0.3, 0, 1, 1)",
} as const;

export type TokenKey = keyof typeof light;
export type Theme = typeof light;

/** CSS-Variablenreferenz zu einem Token, z. B. cssVar('color-accent') === 'var(--color-accent)'. */
export const cssVar = (key: TokenKey): string => `var(--${key})`;

/** Default-Theme (hell). Rohwerte; für Theming bevorzugt cssVar() nutzen. */
export const tokens = light;
